name: "build-client"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - "client/**"
  pull_request:
    branches:
      - "main"
      - "master"
    paths:
      - "client/Dockerfile*"
      - "client/requirements.txt"

jobs:
  docker_buildx_debian:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Perform setup steps
        uses: JonasAlfredsson/checkout-qemu-buildx@v2
        with:
          should_login: ${{ github.event_name != 'pull_request' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version numbers from requirements.txt
        run: bash .github/version_extractor.sh client/requirements.txt client >> $GITHUB_ENV

      - name: Build and push latest Debian image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            loveyu/devpi-client:latest
            loveyu/devpi-client:${{ env.APP_MAJOR }}
            loveyu/devpi-client:${{ env.APP_MAJOR }}.${{ env.APP_MINOR }}
            loveyu/devpi-client:${{ env.APP_MAJOR }}.${{ env.APP_MINOR }}.${{ env.APP_PATCH }}


  docker_buildx_alpine:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Perform setup steps
        uses: JonasAlfredsson/checkout-qemu-buildx@v2
        with:
          should_login: ${{ github.event_name != 'pull_request' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version numbers from requirements.txt
        run: bash .github/version_extractor.sh client/requirements.txt client >> $GITHUB_ENV

      - name: Build and push latest Alpine image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./client
          file: ./client/Dockerfile-alpine
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            loveyu/devpi-client:latest-alpine
            loveyu/devpi-client:${{ env.APP_MAJOR }}-alpine
            loveyu/devpi-client:${{ env.APP_MAJOR }}.${{ env.APP_MINOR }}-alpine
            loveyu/devpi-client:${{ env.APP_MAJOR }}.${{ env.APP_MINOR }}.${{ env.APP_PATCH }}-alpine
